POST https://jsonplaceholder.typicode.com/posts

Content-Type: application/json

{
        "title": "post1",
        "body": "Body post 1",
}

################################

POST http://localhost:3000/api/post

{
        "title": "post1",
         "body": "Body post 1",
      
}


