POST http://localhost:3000/api/post/

Content-Type: application/json

{
    "title":"Lorem"
}

################################
POST https://jsonplaceholder.typicode.com/posts
Content-Type: "application/json"

{
    "x": "zzzzz"
}